env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - google
  - plugin:react/jsx-runtime
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {
  "object-curly-spacing": ["error", "always"]
}
ignorePatterns:
  - "src/**/*.test.ts"
  - "src/**/*.test.tsx"
  - "src/**/*.d.ts"
